services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # healthcheck:
#     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
#     interval: 30s
#     timeout: 10s
#     retries: 3
#     start_period: 40s
    restart: unless-stopped
    networks:
      - transformer-viz-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    # depends_on:
#       backend:
#         condition: service_healthy
    restart: unless-stopped
    networks:
      - transformer-viz-network

networks:
  transformer-viz-network:
    driver: bridge
